# Generated by Django 4.1.7 on 2023-07-25 19:59

import buildup_app.customized_fields
import buildup_app.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True, db_column='creation_date')),
                ('status', buildup_app.customized_fields.UpperCaseCharField(db_column='status', default='PENDING', max_length=20, validators=[buildup_app.validators.validate_building_permit_status])),
                ('approval_date', models.DateField(blank=True, db_column='approval_date', null=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
            ],
            options={
                'db_table': 'building_permit',
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256, unique=True)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.RESTRICT, related_name='section_template', to='buildup_app.company')),
            ],
            options={
                'db_table': 'section_template',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', buildup_app.customized_fields.UpperCaseCharField(db_column='role', max_length=20, validators=[buildup_app.validators.validate_role])),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.RESTRICT, related_name='profile', to='buildup_app.company')),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.RESTRICT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='FileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.RESTRICT, related_name='file_template', to='buildup_app.company')),
            ],
            options={
                'db_table': 'file_template',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('link', models.FileField(db_column='link', max_length=256, upload_to='company_file_uploads')),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('company', models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.RESTRICT, related_name='company_file', to='buildup_app.company')),
            ],
            options={
                'db_table': 'company_file',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BuildingPermitSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=256)),
                ('content', models.CharField(db_column='content', max_length=500)),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('building_permit', models.ForeignKey(db_column='building_permit', on_delete=django.db.models.deletion.RESTRICT, related_name='building_permit_section', to='buildup_app.buildingpermit')),
                ('section_template', models.ForeignKey(db_column='section_template', on_delete=django.db.models.deletion.RESTRICT, related_name='building_permit_section', to='buildup_app.sectiontemplate')),
            ],
            options={
                'db_table': 'building_permit_section',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BuildingPermitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=256)),
                ('link', models.FileField(db_column='link', max_length=256, upload_to='building_permit_file_uploads')),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('building_permit', models.ForeignKey(db_column='building_permit', on_delete=django.db.models.deletion.RESTRICT, related_name='building_permit_file', to='buildup_app.buildingpermit')),
                ('file_template', models.ForeignKey(db_column='file_template', on_delete=django.db.models.deletion.RESTRICT, related_name='building_permit_file', to='buildup_app.filetemplate')),
            ],
            options={
                'db_table': 'building_permit_file',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='buildingpermit',
            name='company',
            field=models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.RESTRICT, related_name='building_permit', to='buildup_app.company'),
        ),
        migrations.AddField(
            model_name='buildingpermit',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.RESTRICT, related_name='building_permit', to=settings.AUTH_USER_MODEL),
        ),
    ]
