# Generated by Django 4.1.7 on 2023-07-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_column='name', max_length=256),
        ),
    ]
