# Generated by Django 4.1.7 on 2023-07-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup_app', '0004_rename_name_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(db_column='company_name', max_length=256, unique=True),
        ),
    ]
