# Generated by Django 4.1.7 on 2023-07-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup_app', '0006_rename_company_name_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_column='name', max_length=256, unique=True),
        ),
    ]
