# Generated by Django 4.1.7 on 2023-08-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildup_app', '0007_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingpermit',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='buildingpermitfile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='buildingpermitsection',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='companyfile',
            name='is_deleted',
        ),
    ]
