# Generated by Django 4.1.7 on 2023-08-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup_app', '0008_remove_buildingpermit_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='approval_date',
            field=models.DateField(blank=True, db_column='approval_date', default=None, null=True),
        ),
    ]
