# Generated by Django 4.1.7 on 2023-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildup_app', '0009_alter_buildingpermit_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfile',
            name='link',
            field=models.CharField(db_column='link', max_length=256),
        ),
    ]
